### ISSUE TITLE
test262.report results are not updated from 2020 12/16

### ISSUE THREAD

**Issue by Constellation** [bocoup/test262-report-issue-tracker#25] opened 2021-01-05 01:59 UTC
### Summary

test262.report's data is not updated from 2020/12/16

### Expected behavior

Updated daily.

### Actual behavior

Not updated from 12/16.

### Steps to reproduce

Open test262.report to check data

### Environment

N/A

**Comment by rwaldron** [comment] 2021-01-05 14:16
@Constellation this is a known issue. The Circle CI setup lost its follower, so it's not running builds. I believe @jugglinmike has, or will address this as soon as possible.

**Comment by Constellation** [comment] 2021-01-06 07:42
@rwaldron Thank you so much :D

**Comment by rwaldron** [comment] 2021-01-06 14:07
@Constellation no problem!

**Comment by Constellation** [comment] 2021-01-29 23:30
@rwaldron @jugglinmike Hi! Is there any update on this?

**Comment by Constellation** [comment] 2021-02-26 00:18
@rwaldron Sorry for troubling you. Do you have an update on this?

**Comment by jugglinmike** [comment] 2021-02-26 04:06
No update. I will post here when I know more.

**Comment by jugglinmike** [comment] 2021-03-03 16:32
Automated results collection has been restored

**Comment by Constellation** [comment] 2021-03-03 19:41
@jugglinmike Awesome! Thanks so much!!!

**Comment by jugglinmike** [comment] 2021-03-05 17:21
I spoke too soon. Although the system correctly reported results one time this week, it has not repeated the task since. Re-opening until this is resolved.

**Comment by Constellation** [comment] 2021-04-14 00:39
It seems that some of URLs that were visible are not accessible (e.g. https://test262.report/?date=2021-03-16).

**Comment by Constellation** [comment] 2021-08-28 22:20
Looks like it is down from 8/15.

**Comment by jugglinmike** [comment] 2021-10-05 17:40
This project has been posting new test results as of mid-September, so I'm going to close this issue.

> It seems that some of URLs that were visible are not accessible (e.g. https://test262.report/?date=2021-03-16).

That link appears to be working as intended for me, now. If it's still a problem for anyone, please open a new issue

**Closed as completed by jugglinmike** 2021-10-05 17:40 UTC
